framework:
    notifier:
        texter_transports:
            sendgrid: '%env(MAILER_DSN)%'
            win_toast: 'App\Notifier\Notification'
        channel_policy:
            # Specify the priority levels and the corresponding channels for each level
            urgent: ['win_toast']
            high: ['win_toast']
            medium: ['win_toast']
            low: ['win_toast']

