search_product:
    path: /search/product
    controller: 'App\Controller\ProductController::search'
    methods: ['GET']

#index:
#    path: /
#    controller: App\Controller\DefaultController::index
user_nutrition_new:
    path: '/user_nutrition/new'
    controller: App\Controller\UserNutritionController::new

user_nutrition_edit:
    path: /user/nutrition/edit/{id}
    controller: App\Controller\UserNutritionController::edit

user_nutrition_index:
    path: /user/nutrition
    controller: App\Controller\UserNutritionController::index    

recipe_analyzer:
    path: /get-regime
    controller: App\Controller\RecipeAnalyzerController::index    


# ai bot 
botman:
    path: /botman
    controller: App\Controller\BotManController::index

botman_handle:
    path: /botman/chat
    controller: App\Controller\BotManController::handle
#index:
#    path: /
#    controller: App\Controller\DefaultController::index4

app_recipe_analyzer:
    path: /recipe/analyzer
    controller: App\Controller\RecipeAnalyzerController::index
    methods: ['GET']

app_analyzer:
    path: /recipe/analyze
    controller: App\Controller\RecipeAnalyzerController::analyze
    methods: ['GET', 'POST']

app_favorite_show:
    path: /show_favorite
    controller: App\Controller\RecettesController::favoriteRecipes
    methods: ['GET']

search_recipes:
    path: /search
    controller: App\Controller\RecettesController::searchRecipes
    methods: ['GET']

filtrer_recettes:
    path: /filter
    controller: App\Controller\RecettesController::filterRecipes
    methods: ['GET']
