#index:
#    path: /
#    controller: App\Controller\DefaultController::index4

app_recipe_analyzer:
    path: /recipe/analyzer
    controller: App\Controller\RecipeAnalyzerController::index
    methods: ['GET']

app_analyzer:
    path: /recipe/analyze
    controller: App\Controller\RecipeAnalyzerController::analyze
    methods: ['GET', 'POST']

app_favorite_show:
    path: /show_favorite
    controller: App\Controller\RecettesController::favoriteRecipes
    methods: ['GET']

search_recipes:
    path: /search
    controller: App\Controller\RecettesController::searchRecipes
    methods: ['GET']

filtrer_recettes:
    path: /filter
    controller: App\Controller\RecettesController::filterRecipes
    methods: ['GET']

app_mesRecettes_show:
    path: /mes_recettes
    controller: App\Controller\RecettesController::MesRecettesChef
    methods: ['GET']

