# The entry point to configure your own services.

parameters:
    # Define any parameters your application needs here.
    # Example:
    # my_custom_parameter: 'value'

services:
    # Default configuration for services in this file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # By default, services are private unless explicitly made public.

    # Autowire classes in the App\ namespace as services
    App\:
        resource: '../src/'  # Load classes from the src/ directory
        exclude:
            - '../src/DependencyInjection/'  # Exclude dependency injection configuration
            - '../src/Entity/'              # Exclude Doctrine entities
            - '../src/Kernel.php'           # Exclude Kernel.php
        public: true

    # Define StripeService
    
    Knp\Snappy\GeneratorInterface:
        alias: knp_snappy.pdf
    # Define other services and configurations as needed

    # Define the ToastrFactory service
    Flasher\Toastr\Prime\ToastrFactory:
        public: true  # Allow this service to be autowired
