
# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

parameters:
    uploads_directory: '%kernel.project_dir%/public/usersProfile'
    app.apiTranslateKey: '%env(API_TRANSLATE_KEY_VALUE)%'
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'

services:
    # Default configuration for services in this file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # By default, services are private unless explicitly made public.

    # Autowire classes in the App\ namespace as services
    App\:
        resource: '../src/'  # Load classes from the src/ directory
        exclude:
            - '../src/DependencyInjection/'  # Exclude dependency injection configuration
            - '../src/Entity/'              # Exclude Doctrine entities
            - '../src/Kernel.php'           # Exclude Kernel.php
        public: true
        

    App\Twig\AppExtension:
        tags:
            - { name: twig.extension }   
            
    
             

    App\Service\ChatGPTService:
          arguments:
              $httpClient: '@http_client'
              $apiKey: 'sk-proj-hCtKDfWwJm91rvritxXdT3BlbkFJ9YtpEs3UguKTSFtjU23p'

    # Define StripeService
    
    Knp\Snappy\GeneratorInterface:
        alias: knp_snappy.pdf
    # Define other services and configurations as needed

    # Define the ToastrFactory service
    Flasher\Toastr\Prime\ToastrFactory:
        public: true  # Allow this service to be autowired
    # Define your controller as a service
    App\Controller\AdminUserNutritionController:
        tags: ['controller.service_arguments']
